import { beforeEach, describe, expect, it, vi } from "vitest";
import { autoGenerateDrafts } from "./auto-generate.js";

// Mock 依赖
vi.mock("./pending-store.js", () => ({
	listPendingTopics: vi.fn(),
	updatePendingTopicStatus: vi.fn(),
}));

vi.mock("./web-enricher.js", () => ({
	enrichContext: vi.fn(),
	formatEnrichmentForPrompt: vi.fn(),
}));

import { listPendingTopics } from "./pending-store.js";
import { enrichContext, formatEnrichmentForPrompt } from "./web-enricher.js";

const mockListPendingTopics = vi.mocked(listPendingTopics);
const mockEnrichContext = vi.mocked(enrichContext);
const mockFormatEnrichmentForPrompt = vi.mocked(formatEnrichmentForPrompt);

describe("autoGenerateDrafts", () => {
	beforeEach(() => {
		vi.clearAllMocks();
	});

	it("无待审选题时返回空结果", async () => {
		mockListPendingTopics.mockResolvedValue([]);
		const result = await autoGenerateDrafts();
		expect(result.generated).toBe(0);
		expect(result.drafts).toHaveLength(0);
	});

	it("置信度不足时跳过", async () => {
		mockListPendingTopics.mockResolvedValue([
			{
				id: "t1",
				sourceUrl: "https://example.com/1",
				siteName: "test",
				title: "低置信度",
				facts: { 作品名: "作品A" },
				confidence: 0.3,
				status: "pending",
				createdAt: "",
				updatedAt: "",
			},
		] as any);
		const result = await autoGenerateDrafts({ minConfidence: 0.5 });
		expect(result.skipped).toBe(1);
		expect(result.generated).toBe(0);
	});

	it("高置信度选题被处理", async () => {
		mockListPendingTopics.mockResolvedValue([
			{
				id: "t2",
				sourceUrl: "https://example.com/2",
				siteName: "test",
				title: "高置信度",
				facts: { 作品名: "作品B", 制作: "作者B" },
				confidence: 0.8,
				status: "pending",
				createdAt: "",
				updatedAt: "",
			},
		] as any);
		const result = await autoGenerateDrafts({ minConfidence: 0.5 });
		expect(result.skipped).toBe(1);
		expect(result.generated).toBe(0);
	});

	it("高置信度选题被处理", async () => {
		mockListPendingTopics.mockResolvedValue([
			{
				id: "t2",
				sourceUrl: "https://example.com/2",
				siteName: "test",
				title: "高置信度",
				facts: { 作品名: "作品B", 制作: "作者B" },
				confidence: 0.8,
				status: "pending",
				createdAt: "",
				updatedAt: "",
			},
		] as any);
		mockEnrichContext.mockResolvedValue({
			queryResults: [],
			collectedAt: "",
		});
		mockFormatEnrichmentForPrompt.mockReturnValue("");

		const result = await autoGenerateDrafts();
		expect(result.generated).toBe(1);
		expect(result.drafts[0].title).toBe("高置信度");
		expect(result.drafts[0].facts.作品名).toBe("作品B");
	});

	it("富化失败时不影响主流程", async () => {
		mockListPendingTopics.mockResolvedValue([
			{
				id: "t3",
				sourceUrl: "https://example.com/3",
				siteName: "test",
				title: "测试",
				facts: { 作品名: "作品C" },
				confidence: 0.7,
				status: "pending",
				createdAt: "",
				updatedAt: "",
			},
		] as any);
		mockEnrichContext.mockRejectedValue(new Error("网络错误"));

		const result = await autoGenerateDrafts();
		expect(result.generated).toBe(1);
		expect(result.errors).toBe(0);
	});

	it("maxItems 限制生成数量", async () => {
		const topics = Array.from({ length: 10 }, (_, i) => ({
			id: `t${i}`,
			sourceUrl: `https://example.com/${i}`,
			siteName: "test",
			title: `作品${i}`,
			facts: { 作品名: `作品${i}` },
			confidence: 0.8,
			status: "pending" as const,
			createdAt: "",
			updatedAt: "",
		}));
		mockListPendingTopics.mockResolvedValue(topics as any);
		mockEnrichContext.mockResolvedValue({ queryResults: [], collectedAt: "" });
		mockFormatEnrichmentForPrompt.mockReturnValue("");

		const result = await autoGenerateDrafts({ maxItems: 3 });
		expect(result.generated).toBe(3);
	});
});
