// 自动批量生成草稿：从待审选题池获取高置信度选题，自动生成草稿。
// 用于定时任务或手动触发，减少人工干预。

import type { FactsBlock } from "@51publisher/shared";
import { extractFacts } from "./fact-extractor.js";
import {
	listPendingTopics,
	type PendingTopic,
	updatePendingTopicStatus,
} from "./pending-store.js";
import { enrichContext, formatEnrichmentForPrompt } from "./web-enricher.js";

export interface AutoGenerateOptions {
	/** 最低置信度（默认 0.5）。 */
	minConfidence?: number;
	/** 单次最多生成数（默认 5）。 */
	maxItems?: number;
	/** 是否启用富化（默认 true）。 */
	enableEnrichment?: boolean;
}

export interface AutoGenerateResult {
	/** 成功生成的草稿数。 */
	generated: number;
	/** 跳过的选题数（置信度不足等）。 */
	skipped: number;
	/** 出错数。 */
	errors: number;
	/** 生成的草稿列表。 */
	drafts: Array<{
		topicId: string;
		title: string;
		facts: FactsBlock;
		enrichment?: string;
	}>;
}

export interface AutoGenerateDeps {
	llmEndpoint: string;
	llmApiKey: string;
	llmModel?: string;
}

/**
 * 自动批量生成草稿。
 * 从 pending_topics 表获取高置信度选题，提取事实并富化，返回可直接用于生成草稿的数据。
 */
export async function autoGenerateDrafts(
	deps: AutoGenerateDeps,
	opts: AutoGenerateOptions = {},
): Promise<AutoGenerateResult> {
	const { minConfidence = 0.5, maxItems = 5, enableEnrichment = true } = opts;

	const result: AutoGenerateResult = {
		generated: 0,
		skipped: 0,
		errors: 0,
		drafts: [],
	};

	// 获取待审选题（按置信度降序）
	const topics = await listPendingTopics(maxItems * 2, "pending", "score");

	for (const topic of topics) {
		if (result.generated >= maxItems) break;

		// 检查置信度
		if (topic.confidence < minConfidence) {
			result.skipped++;
			continue;
		}

		try {
			const facts = topic.facts;

			// Web 搜索富化
			let enrichmentText = "";
			if (enableEnrichment && (facts.制作 || facts.作品名)) {
				try {
					const ctx = await enrichContext({
						facts,
						maxQueries: 2,
						timeoutMs: 10_000,
					});
					enrichmentText = formatEnrichmentForPrompt(ctx);
				} catch {
					// 富化失败不影响主流程
				}
			}

			result.drafts.push({
				topicId: topic.id,
				title: topic.title,
				facts,
				...(enrichmentText ? { enrichment: enrichmentText } : {}),
			});

			result.generated++;
		} catch (err) {
			result.errors++;
		}
	}

	return result;
}
